### ISSUE TITLE
안녕하세요 과정에 대해 궁금합니다.

### ISSUE THREAD

**Issue by cyberjam** [No-longlong/Finance_Analysis_Python#1]
안녕하세요 데이터 청년 캠퍼스 교육 과정에 대해 궁금합니다.
어떤 커리큘럼이고 우수팀 프로젝트는 어떤 주제이며 어느정도로 잘했는지 궁금합니다 고맙습니다

**Comment by No-longlong** [comment]
안녕하세요.
상명대학교에서 진행된 데이터청년캠퍼스는 금융빅데이터분석이라는 큰 주제를 놓고 
1.주식(2팀), 2.금융(4팀) 으로 나눠서 프로젝트를 진행했습니다.
커리큘럼은 전 학생 모두 동일하게 온-오프라인으로 진행하였습니다.
커리에 대한 자세한 내용은 금일내로 README에 재업로드를 시켜놓겠습니다.
우수팀은 아직 정해지지 않았고 아직 진행중에 있습니다.
이 결과는 추후에 데이터청년캠퍼스 주관측에서 종합하여 자료를 업로드 할 예정이라고 들었습니다.

**Comment by cyberjam** [comment]
네 답변 감사합니다. 어떤 세부 주제로 진행하실지 매우 궁금하군요😀 우수작이 언제 나올지 모르겠지만 관련 소식 있다면 관련 내용 공유 부탁드려도 괜찮을까요? 답변 다시 한번 감사합니다.

**Comment by No-longlong** [comment]
예 제가 모든 조의 내용을 알 수 있을진 모르겠지만, 내용이 공유 가능한 사안이라면 알려드리도록 할게요 👍

**Comment by No-longlong** [comment]
예 제가 모든 조의 내용을 알 수 있을진 모르겠지만, 내용이 공유 가능한 사안이라면 알려드리도록 할게요 👍
